const units=["01 사회·문화 현상의 이해","02 사회·문화 현상의 연구 방법","03 자료 수집 방법","04 사회·문화 현상의 탐구 태도와 연구 윤리","05 사회적 존재로서의 인간","06 사회 집단과 사회 조직","07 사회 구조와 일탈 행동","08 문화의 이해","09 현대 사회의 문화 양상","10 문화 변동의 양상과 대응","11 사회 불평등 현상의 이해","12 사회 이동과 사회 계층 구조","13 다양한 사회 불평등 현상","14 사회 복지와 복지 제도","15 사회 변동과 사회 운동","16 현대 사회의 변화와 전 지구적 수준의 문제"];
const KEY="socmun_v3";let data=JSON.parse(localStorage.getItem(KEY)||"null")||{exams:[],cells:{},recent:false};
const today=()=>{let d=new Date();return d.toISOString().slice(0,10)};
const valid=d=>/^\d{4}-\d{2}-\d{2}$/.test(d);
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function sort(){data.exams.sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name))}
function recent(d){let x=new Date();x.setHours(23,59,59,999);let s=new Date(x);s.setDate(s.getDate()-6);s.setHours(0,0,0,0);return new Date(d+"T00:00:00")>=s&&new Date(d+"T00:00:00")<=x}
function cycle(k){data.cells[k]=(data.cells[k]||0)%3+1;if(data.cells[k]===3)data.cells[k]=0;save();render()}
function add(){let name=prompt("모의고사 이름을 입력하세요.","9월 평가원");if(name===null)return;let date=prompt("응시 날짜(YYYY-MM-DD)",today());if(date===null)return;if(!valid(date))date=today();data.exams.push({id:String(Date.now()+Math.random()),name:name.trim()||"모의고사",date});sort();save();render()}
function rate(ui){let w=0,t=0;data.exams.forEach(e=>{if(data.recent&&!recent(e.date))return;let v=data.cells[e.id+":"+ui]||0;if(v===1||v===2){t++;if(v===2)w++}});return t?((w/t)*100).toFixed(1)+"%":"—"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(){sort();let t=document.querySelector("#tbl"),rs=data.recent?data.exams.filter(e=>recent(e.date)):data.exams;if(data.recent&&!rs.length){t.innerHTML='<thead><tr><th class="unit">단원</th><th class="rate rate-header">오답률<div class="rate-toggle"><label class="switch"><input id="sw" type="checkbox" checked><span class="slider"></span></label>최근 1주 오답률</div></th></tr></thead><tbody><tr><td colspan="2" class="empty-message">최근 1주동안 응시한 모의고사가 없습니다</td></tr></tbody>';document.querySelector("#sw").onchange=e=>{data.recent=e.target.checked;save();render()};return}
let h='<thead><tr><th class="unit">단원</th>';data.exams.forEach((e,i)=>h+=`<th class="exam"><input class="exam-name" value="${esc(e.name)}" data-i="${i}"><input class="date-input" type="date" value="${e.date}" data-i="${i}"><br><button class="delete" data-i="${i}">삭제</button></th>`);h+='<th class="rate rate-header">오답률<div class="rate-toggle"><label class="switch"><input id="sw" type="checkbox" '+(data.recent?"checked":"")+'><span class="slider"></span></label>최근 1주 오답률</div></th></tr></thead><tbody>';
units.forEach((u,ui)=>{h+=`<tr><td class="unit">${u}</td>`;data.exams.forEach(e=>{let v=data.cells[e.id+":"+ui]||0;h+=`<td class="cell ${v===1?"white":v===2?"black":"empty"}" data-k="${e.id}:${ui}">${v===1?"⚪️":v===2?"⚫️":"·"}</td>`});h+=`<td class="rate">${rate(ui)}</td></tr>`});t.innerHTML=h+"</tbody>";
document.querySelectorAll(".cell").forEach(x=>x.onclick=()=>cycle(x.dataset.k));
document.querySelectorAll(".exam-name").forEach(x=>x.onchange=()=>{data.exams[+x.dataset.i].name=x.value||"모의고사";save();render()});
document.querySelectorAll(".date-input").forEach(x=>x.onchange=()=>{if(valid(x.value)){data.exams[+x.dataset.i].date=x.value;save();render()}});
document.querySelectorAll(".delete").forEach(x=>x.onclick=()=>{if(confirm("이 모의고사를 삭제할까요?")){let e=data.exams.splice(+x.dataset.i,1)[0];Object.keys(data.cells).forEach(k=>{if(k.startsWith(e.id+":"))delete data.cells[k]});save();render()}});
document.querySelector("#sw").onchange=e=>{data.recent=e.target.checked;save();render()}}
function backup(){let a=document.createElement("a"),b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="사회문화_오답기록.json";a.click();URL.revokeObjectURL(a.href)}
function restore(){let i=document.createElement("input");i.type="file";i.accept=".json";i.onchange=()=>{let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.exams)||!x.cells)throw 0;data=x;data.exams.forEach((e,i)=>{e.id=String(e.id||Date.now()+i);e.date=valid(e.date)?e.date:today()});save();render();alert("복원되었습니다.")}catch{alert("올바른 JSON 백업 파일이 아닙니다.")}};r.readAsText(i.files[0])};i.click()}
document.querySelector("#add").onclick=add;document.querySelector("#backup").onclick=backup;document.querySelector("#restore").onclick=restore;document.querySelector("#reset").onclick=()=>{if(confirm("전체 데이터를 삭제할까요?")){data={exams:[],cells:{},recent:false};save();render()}};render();